### PR TITLE
Fix: not showing dropdowns after sort column

### PR DESCRIPTION
**Pull request by vildanbina**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests and did you add any new tests needed for your feature?
2. [ ] Did you update all templates (if applicable)?
3. [ ] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by bureauvk** [comment]
Your fix works, but why? You just deleted some aria-labelledby attributes and id attributes.

**Comment by vildanbina** [comment]
> Your fix works, but why? You just deleted some aria-labelledby attributes and id attributes.

after dropdown replaced by livewire response, I don't know why alpine js version 3 has crashed from id attribute

**Comment by rappasoft** [comment]
Just because it works doesn't mean it's a viable fix. We need to understand why it's behaving that way so we can properly fix it.

**Comment by bureauvk** [comment]
> Going to merge for now but it's not a permanent fix.

I don't know if it's worth mentioning, but in the demo it seems to work fine. Or is the demo running on the V2?

**Pull request merged**
