### PR TITLE
Adds an option set a search placeholder

### PR DESCRIPTION
**Pull request by limewebdevelopment**
I had a requirement to set the search placeholder. This can be set in the `configure()` like this `$this->setSearchPlaceholder('Search documents');`

Not setting returns the default translatable string.

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests and did you add any new tests needed for your feature?
2. [ ] Did you update all templates (if applicable)?
3. [ ] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. [ ] Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by lrljoe** [comment]
Think there may be some formatting that needs fixing on your PR, as I'm seeing large differences in the blade, which is making it a bit difficult to assess.

I'll look at it in a separate branch this weekend.

**Comment by limewebdevelopment** [comment]
Just noticed that, I think phpStorm tidied it. 

Will try to resubmit too

**Comment by lrljoe** [comment]
Cheers, if you run php cs fixer against the file with the config in the root folder, then it'll bring it back into line with everything else.

I've also updated your PR to go against develop as that's where we merge all PRs, then Anthony picks up develop and merges it into master before the release.  But I've noticed a diff between develop "README" and yours, not sure what's changed as I'm on mobile, but that file shouldn't need updating really unless something massive has changed!

**Comment by lrljoe** [comment]
Apologies for not getting this merged across sooner, if you can update your README file to reflect th e develop branch then that'd be great, no biggy if you don't have time tho!

**Comment by limewebdevelopment** [comment]
Leave it with me, I'll resubmit - no rush

**Comment by lrljoe** [comment]
Appreciated, I'm planning to do some reviews and merging into develop later this weekend/on Monday, if its ready by then, great, if not, no drama, as the release probably won't be until the following weekend anyway.

**Comment by lrljoe** [comment]
Also, can you make sure $searchPlaceholder is defined in the appropriate place please! :)

Keen to get this merged in rather than copy your work into a fresh branch to merge it in!  But let me know if you won't have time in the next week and I can do that if need be.

**Comment by lrljoe** [comment]
Definitions for properties should be in src/Traits/, so in this case src/Traits/WithSearch

**Comment by lrljoe** [comment]
I **will** add this into v3.0

Leave it with me.

**Comment by lrljoe** [comment]
I've adjusted this slightly to match the other functions.

This is in the v3.0 beta at the moment, will update if we pull it for any reason.

**Comment by lrljoe** [comment]
This is in v3.0

I will be looking at various backports to v2.x, and closing off outstanding **bugs**  for v2, this and a handful of other new features will be backported to v2 most likely.

**Comment by lrljoe** [comment]
Adding to backports to-do.  This functionality exists in v3.

**Comment by lrljoe** [comment]
@limewebdevelopment - Note that I've merged another PR for setSearchPlaceholder(), which is a backport from v3.

The bits that were missing from this PR (for future reference)
- Tests for the methods
- Documentation for the method

This PR
[https://github.com/rappasoft/laravel-livewire-tables/pull/1334](https://github.com/rappasoft/laravel-livewire-tables/pull/1334) is the one that was used.  You'll note the similarities!

Really appreciate the commit, I'm still compiling the contributors/with thanks files for v2 & v3 so I'll make sure to note in there.

**Pull request closed without merging**
