### PR TITLE
fix tailwind pagination view

### PR DESCRIPTION
**Pull request by bdelamatre**

### CODE REVIEW

**Comment by rappasoft** [comment]
What's the use case here? Also, the other templates would be unchanged but have the same issue as you are trying to fix. But I feel like we've gone back and forth with the wrapping if statement and I don't remember why haha.

**Comment by bdelamatre** [comment]
The use case is that I have a table, with pagination, but I don't need to show the per-page dropdown. The current behavior is If showPerPage is false then pagination links are hidden.

I forget as well. I think the last time I touched it the goal was to display the result count regardless of whether pagination was enabled or not. This behavior was a little different on the tailwind theme since the bootstrap links() displayed the count reliably while tailwind didn't.

**Comment by rappasoft** [comment]
What about the [$showPerPage](https://github.com/rappasoft/laravel-livewire-tables/wiki/Display) property?

**Comment by bdelamatre** [comment]
I would expect the showPerPage property to be limited to showing/hiding the
per page drop-down.

**Comment by rappasoft** [comment]
What if we just changed it to:

```html
@if ($showPagination)
    <div class="p-6 md:p-0">
        @if ($paginationEnabled && $rows->lastPage() > 1)
            {{ $rows->links() }}
        @else
            <p class="text-sm text-gray-700 leading-5">
                @lang('Showing')
                <span class="font-medium">{{ $rows->count() }}</span>
                @lang('results')
            </p>
        @endif
    </div>
@endif
```

**Comment by bdelamatre** [comment]
Sure.

**Pull request merged**
