### PR TITLE
Add ability to hide filters in the UI

### PR DESCRIPTION
**Pull request by inmanturbo**
As discussed Here https://github.com/rappasoft/laravel-livewire-tables/discussions/759

Includes test and documentation

### CODE REVIEW

**Comment by rappasoft** [comment]
I think it would be cool if the API was as easy as this: 

```php
->secondaryHeader($this->getFilter('active')),
```

Where it inferred the filter type and figured out how to get it in there without the user having to define the closure and the view.

Not sure if possible yet but going to give it a try on this branch.

**Comment by inmanturbo** [comment]
Yes that would be a cool feature as well! This currently only adds the ability to hide the filter in the `popover` and and `slide down`, and doesn't change anything to do with `secondaryHeader()`

**Comment by rappasoft** [comment]
This currently works:

```php
->secondaryHeader($this->getFilterByKey('active'))
->footer($this->getFilterByKey('active')),
```

Just have to support all the filter types now.

Screen Shot 2022-05-05 at 14 46 09

**Comment by rappasoft** [comment]
Screen Shot 2022-05-05 at 14 54 53

Should a header/footer filter update the number badge on the filters button?

**Comment by inmanturbo** [comment]
>Should a header/footer filter update the number badge on the filters button?
You know, that's a good point. `hidden()` filters probably shouldn't update the number badge on the filters button as they won't be visible there, and it could lead to confusion. they should appear in the `applied` `pills`, but maybe not update the badge in the button

**Comment by rappasoft** [comment]
Yeah when I have more time later I'll probably remove it from both by default but add configs to put them back if hidden or something.

**Comment by rappasoft** [comment]
Its like 1am and this has spiraled out of control lol. This is my current API:

```
SelectFilter::make('Active')
    ->notResetByClearButton()
    ->hiddenFromMenus()
    ->hiddenFromPills()
    ->hiddenFromFilterCount(),
```

Also this works for all filter types:

```
BooleanColumn::make('Active')
    ->secondaryHeader($this->getFilterByKey('active'))
    ->footer($this->getFilterByKey('active')),
```

Still a lot of testing/refactor/documentation to do but looks cool.

**Comment by rappasoft** [comment]
Closing for the local branch PR

**Pull request closed without merging**
