### PR TITLE
added appendRender() to render function

### PR DESCRIPTION
**Pull request by shiv122**
### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests and did you add any new tests needed for your feature?
2. [ ] Did you update all templates (if applicable)?
3. [ ] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. [X] Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [X] Have you successfully ran tests with your changes locally?

### Introduction

I had a table where i wanted to show sum of all amount on top of table name stats which was loaded using `setConfigurableAreas()`  function . I did not find any way to do that because it should change on every filter and search.

So i added this `appendRender()` to render function so any once can use that to manipulate variables before render get called.

### CODE REVIEW

**Comment by lrljoe** [comment]
There are other approaches for extracting values for reuse within the component, so I'd suggest opening a discussion for this instead.

You'd also need to write the relevant tests and documentation for any PR.

**Comment by lrljoe** [comment]
There are setConfigurableAreas([]) to update a specific area on component.

Depending on area, these may be able to access $rows etc.

You can use the Livewire lifecycle hooks where appropriate to update other variables.
[https://laravel-livewire.com/docs/2.x/lifecycle-hooks](https://laravel-livewire.com/docs/2.x/lifecycle-hooks)

Otherwise I'd definitely need to see some documentation, tests etc for this please, and perhaps some use cases if I've misunderstood the intended function?

There's also a conflict with the develop branch which will need resolving.

**Comment by shiv122** [comment]
i know about setConfigurableAreas and i used it . trying doing this=> 

You have a table of subscriptions where you need to get sum of all amount ,
after that you have a Tax calculation class that adds taxes on those ,
i need to access data before to manipulate it and assign it to some public variable so i can use it in   blade which i loaded using `setConfigurableAreas ()`

**Comment by lrljoe** [comment]
I see where you're going with that at least now, thanks for the insight!

Can I ask, what's your plan in terms of what you're going to add to your appendRender() function?  

The reason I ask, is the latest results from the query results that will be displayed to the user won't be available at the point where you're calling your function, as the getRows() is what is actually executing the query.  Anything you call before that point will be one lifecycle behind., and therefore inaccurate I'm afraid!

Where getRows() is called is something I'm looking at separately.

**Comment by shiv122** [comment]
when i use ` $this->sum = $this->getRows()->flatten()->pluck('amount')->sum();` 
what if i want to assign multiple public variables based on this value from getRows(), 
i can not use this in getRows() apart from that if in want to use my service classes to calculate something or  calling external apis based on $value or if i have multiple $variables which depends on getRows() i cant assign those as well. 
Thanks for help man, appreciate it

**Comment by shiv122** [comment]
Thank you so much for help.

**Pull request closed without merging**
