### PR TITLE
Typehinting in blade components

### PR DESCRIPTION
**Pull request by edwinvdpol**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests and did you add any new tests needed for your feature?
2. [x] Did you update all templates (if applicable)?
3. [ ] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. [ ] Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

This will improve IDE autocompletion in blade files where applicable.

I would like to cleanup / structurize the blade files even more after this PR to make things more readable and consistent.

### CODE REVIEW

**Comment by lrljoe** [comment]
Wow, lot of changes here! It'll probably be the weekend before I can review this properly.

Really appreciate the contribution!

**Comment by lrljoe** [comment]
Still going through this, why the suggested change from
```
  @isset($tfoot)
```
to
```
  @if (isset($tfoot))
```

```@isset```
is a native Laravel blade helper, that isn't going away any time soon

**Review by lrljoe — COMMENTED** [review]
Mostly reviewed & okay, couple of files left!

**Comment by lrljoe** [comment]
Just the big one (datatable.blade.php) to go, I'll look at that tomorrow, and get this merged in.

**Comment by lrljoe** [comment]
@edwinvdpol - while testing across different versions of PHP & Laravel, it seems that some supported versions presently misbehave with the typehinting in place:

image

This behaviour goes aware without the typehinting.

For the time-being, I'll be rolling back the typehinting in the blades

**Comment by edwinvdpol** [comment]
Not sure what you mean, but allright. 😉
Can you specify which version of PHP and Laravel, and what goes wrong?

**Comment by lrljoe** [comment]
Threw a screenshot on the last update, need to go through and validate the different environments it happens in to know for sure where it's coming from.

Unsure if it's a cdn issue/specific config issue. at the mo, but backing it out resolved it.

Just need to ensure it doesn't break anyone's existing deployments.

**Pull request merged**
