### PR TITLE
Custom view prepend

### PR DESCRIPTION
**Pull request by SimonMacIntyre**
The currently existing `customView` is only suitable for modals and things at the bottom of the page. I really needed something like this as well so that I can do what I have shown in the video comment I added below. 

I would propose renaming `customView` to `customViewAppend` but not worth breaking changes obviously. 

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests and did you add any new tests needed for your feature?
2. [ ] Did you update all templates (if applicable)?
3. [x] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. [x] Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by SimonMacIntyre** [comment]
Example of the feature this unlocks:

https://user-images.githubusercontent.com/1260938/216085328-db764dba-69ad-412a-8e02-424840c35b95.mov

**Comment by SimonMacIntyre** [comment]
I was not aware of `before-toolbar`, and now I am unsure if this is different at all. This was just after I was looking at `Custom View` in isolation, and wondering why an `after` block existed but not a `before`, so I made this. So I am not sure if `before-toolbar` is the exact same functionally as this, or if this offers anything new at all.

**Comment by lrljoe** [comment]
As mentioned on the [Discussion](https://github.com/rappasoft/laravel-livewire-tables/discussions/1035), I'd recommend adding an additional configurableArea if before-toolbar doesn't suit (which it may not due to the filter/sorting pils), over this.

**Comment by SimonMacIntyre** [comment]
> I was not aware of `before-toolbar`, and now I am unsure if this is different at all. This was just after I was looking at `Custom View` in isolation, and wondering why an `after` block existed but not a `before`, so I made this. So I am not sure if `before-toolbar` is the exact same functionally as this, or if this offers anything new at all.

After testing this, it seems there is a difference in how the loading/reaction to variable changes between this and `before-toolbar`. 

Using my already working example, I simply commented out my `customViewPrepend`, and instead used 
```
$this->setConfigurableAreas([
            'before-toolbar' => 'data-table-error'
        ]);
```

But what was interesting, is it did not seem to reload or pick up the variable change and thus show, so it never shows. 
I'm sure there is some way to control that, but to me this means this is different in some way. And I prefer the simplicity of my PR, if I'm being honest, which works as expected intuitively with changing variables. 

I wonder if it is because my custom view prepend is a simple blade view, rather than a livewire component?

**Comment by lrljoe** [comment]
Try using $this->variableName instead, and I imagine it'll work smoothly.

**Comment by SimonMacIntyre** [comment]
> Try using $this->variableName instead, and I imagine it'll work smoothly. Or entangle it with alpine and do it that way.
> 
> I built something very similar for displaying the download links for Exports, but using the before-toolbar area.

Aha.... yes that did it. 

Thanks a lot @lrljoe, appreciate you always being here to help!

**Comment by lrljoe** [comment]
No problem, I'll update those docs in my next PR, and might add a pointer in there around variable access, as no doubt others have had the same issue!

**Pull request closed without merging**
