### PR TITLE
Fix set filter event for multi selectables

### PR DESCRIPTION
**Pull request by edwinvdpol**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests and did you add any new tests needed for your feature?
2. [ ] Did you update all templates (if applicable)?
3. [ ] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. [ ] Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by lrljoe** [comment]
It should also work with this which avoids the "mixed", if it works, then update the commit
```
    public function setFilterEvent(string $filter, string|array $value): void
```

**Comment by edwinvdpol** [comment]
That should also work, but I'd rather keep this in sync with `setFilter()` in `FilterHelpers.php` ([here](https://github.com/rappasoft/laravel-livewire-tables/blob/development/src/Traits/Helpers/FilterHelpers.php#L135)). I will change it anyway.

**Comment by lrljoe** [comment]
Feel free to update the other one as well, happy to have both matching

**Comment by lrljoe** [comment]
I'll merge this in later today, and will look at removing the mixed at a later date if not updated by the time I look at it.

Just did two releases in short-order, so it probably won't actually get released until the middle of the week

**Comment by lrljoe** [comment]
This is now in the latest release, it now accepts, string|array|null to allow for the three defined scenarios

**Pull request closed without merging**
