### PR TITLE
The query-select for the column can be modified or omitted.

### PR DESCRIPTION
**Pull request by LWlook**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests and did you add any new tests needed for your feature?
2. [ ] Did you update all templates (if applicable)?
3. [ ] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. [x] Did you test locally to make sure your feature works as intended?

This pull requests let you hide the table-name prefix in front of some selects in the query. This is helpful to enable sorting and filtering for additional added columns (like with a join). With this pull it is also possible to mitigate some problems related to relationships. (Requested in Issue #874 )

If this pull request would be merged, than I can add the documentation too.

### CODE REVIEW

**Comment by tonypartridge** [comment]
Amazing stuff! I was just going to dig down on this now. The problem with how V2 works is that because we have already defined the select in the query builder it's trying to select it again as part of column make.

My example is:

`php   ::query()->withSum('CYTD as cytd_total', 'total_amount');`
                    
cytd_total has been set, but we then try setting it as cytd with:

 ```php
           Column::make('Total CYTD', 'cytd_total')
                ->format(fn($v) => number_format((float) $v, 2))
                ->sortable(),
```
                
We could look at a different setter? 

isColumnPreSelected

?

**Comment by tonypartridge** [comment]
Maybe addQuerySelect(false) seems the most readable, then you wouldn't need to include table prefix option?

**Comment by LWlook** [comment]
Yes, addQuerySelect(false) would probably be more readable. Or alternativ `excludeFromQuerySelect()`.
But in my changes I only exclude the prefix, not the whole column name. Should work in your example too.
Would than look like that:

```php
          Column::make('Total CYTD', 'cytd_total')
               ->addQuerySelect(false)
               ->format(fn($v) => number_format((float) $v, 2))
               ->sortable(),
```

@rappasoft What is your opinion on this pull request?

**Comment by tonypartridge** [comment]
So you example doesn't work for me because when you include it in the queryBuilder as a join / sum then you define it and it trys to get it again with the same prefix as it's already been defined. Your code isn't checking if it has been defined which is where the excludeFromQuerySelect() or addQuerySelect(false) works. I've overrode the code function for now to work on it.

But @rappasoft  seems to have been silently recently :'(

**Comment by LWlook** [comment]
@tonypartridge What do you think about having a method like `modifyQuerySelect(String? select)`? So you can remove the select completely with `modifyQuerySelect()` or `modifyQuerySelect("")` and I don't have to write every join column to the additionalSelects so I can write them directly to the column definition. (Has the benefit that everything is in one place, and the select will not be triggered if the column is hidden).
Additionally with this method someone has still the ability to remove just the prefix.

**Comment by TonyPartridgeR** [comment]
That sounds much more viable long term, we wouldn't need to do the prefix changing as we are selecting to column. we can empty it out. 

Spoke with Rappasoft too, he's just a bit busy at the moment but is hoping to spend some time on this project soon. 

If you are happy to do a PR we can review and test ;-)

**Comment by LWlook** [comment]
@tonypartridge What do you say to my changes?

**Comment by TonyPartridgeR** [comment]
They look good, but I need to test them out today. I’ve just been a bit waylaid!

**Comment by tonypartridge** [comment]
Looking at this, it would make more sense if we could use the query builder. IT only allows string based SQL

**Comment by tonypartridge** [comment]
Example:

  (
    select 
      sum(
        `laravel_reserved_0`.`total`
      ) 
    from 
      `records` as `laravel_reserved_0` 
    where 
      `records`.`pp_id` = `laravel_reserved_0`.`pp_id` 
      and `period` between '2022-01-01' 
      and '2022-11-03' 
      and `laravel_reserved_0`.`deleted_at` is null
  ) as `cytd_calc`
  
  Cannot be included as far as I ca see within the modifyQuerySelect method. I can now reference the select if I am handling it in the builder function. But the builder doesn't get the filtered values. So ideally we need support to allow optimising the select. In my case I want to pass a filter into the query select essentially, which is very close but not yet workable.

**Comment by TonyPartridgeR** [comment]
Thanks @LWlook, I've moved to filamentphp tables and forms now since it actually does all this.

**Comment by LWlook** [comment]
Probably I should also take a look at another library.

**Comment by TonyPartridgeR** [comment]
It is a shame as it has great potential! But once you checkout filamentphp it's insanely good. Hit me up if you need any pointers.

**Comment by rappasoft** [comment]
Sorry i've been MIA. I'm trying to get into this PR but I think I need a crash course on what we're trying to do.

**Comment by tonypartridge** [comment]
@rappasoft the idea is to allow modifying the select Query of the column. Example is that if you build the select or join into the builder but then define the column, it can be needed to modify the select. The current way isn't possible so this method was proposed. 

I've moved to Filamentphp Forms and Tables now which allowed me to do it and with their admin panel outside the need for forms/tables it just makes everything rapid.

**Pull request closed without merging**
