### PR TITLE
Collapse on all

### PR DESCRIPTION
**Pull request by horsebuzz**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests and did you add any new tests needed for your feature?
2. [x] Did you update all templates (if applicable)?
3. [x] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. [x] Did you test locally to make sure your feature works as intended?

### Changes to Core Features:
This PR adds a third option `collapseOnAll`, which will collapse applicable column on all screen sizes. This is an additional feature and other 2 option will works as usual.

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by rappasoft** [comment]
Shows a plus button even if there is nothing set to collapseOnAll

**Comment by lrljoe** [comment]
@horsebuzz - I had the same issue when I created a version of this, can't remember exactly how I got around it. I'll take a look in my massive list of branches for this and revert!

**Comment by lrljoe** [comment]
> Shows a plus button even if there is nothing set to collapseOnAll

@horsebuzz - I had the same issue when I created a version of this, can't remember exactly how I got around it. I'll take a look in my massive list of branches for this and revert!

**Comment by lrljoe** [comment]
@horsebuzz  - I managed to find my original code and slapped it into a fork of your branch.  It **is** janky as all hell, as it has to check for Collapsed Columns, and figure out if they're empty or not on a per-row basis.  I'd really recommend not doing it this way at all.  But shows you an approach at least!

[Changes Visible Here](https://github.com/LowerRockLabs/laravel-livewire-tables/blob/CollapseOnAll/resources/views/components/table/td/row-contents.blade.php)

**Comment by lrljoe** [comment]
@horsebuzz are you working on this, if not I should have time after the weekend to take a look at it.

**Comment by horsebuzz** [comment]
@lrljoe No, I can not work on it now. I can probably after a month or so. Thank you

**Comment by lrljoe** [comment]
> @lrljoe No, I can not work on it now. I can probably after a month or so. Thank you

No problem, just wanted to make sure your hard work hadn't been abandoned, as the idea is a great one!

**Comment by rappasoft** [comment]
Let me know if this is still in progress.

**Pull request closed without merging**
