### PR TITLE
adding exported property

### PR DESCRIPTION
**Pull request by abdosaeedelhassan**

### CODE REVIEW

**Comment by rappasoft** [comment]
For?

**Comment by abdosaeedelhassan** [comment]
To set the column available for exporting or not

**Comment by rappasoft** [comment]
Why would this be needed? It would not be used anywhere?

**Comment by abdosaeedelhassan** [comment]
we can used like next
`  Column::make(__('Actions'))
                ->format(function ($value, $column, $row) {
                   ....
                    return $html;
                })->asHtml()->exported(false)`

to determine this column is available for exporting to (pdf, excel, ...) or not

**Pull request closed without merging**
