### PR TITLE
Added multiselect filter

### PR DESCRIPTION
**Pull request by Ypho**
I've added a multiselect option filter.

### CODE REVIEW

**Comment by Majkie** [comment]
I'm not exactly sure if its only problem on my side that should be documented, but whenever I want to uncheck one of many checked checkboxes it unchecks all of them.

**Comment by Ypho** [comment]
@Majkie got the same. I thought I fixed it all when I moved from multiselectbox to checkboxes, but I didn't see this. Will try and fix it when I got some time.

**Comment by rappasoft** [comment]
If I dump the values it only returns an array of the most previously selected, even if there are multiple selected.

**Comment by rappasoft** [comment]
I've pumped many hours into trying to get this to work in all scenarios. I have yet to get it to work with both string and numeric array keys. If anyone else has time feel free.

**Comment by juliomotol** [comment]
@rappasoft why was this closed?

**Comment by rappasoft** [comment]
It doesn't work and has been stale.

**Comment by rappasoft** [comment]
Yes, the one here was almost there but it was buggy. Also please modify all 3 templates.

**Pull request closed without merging**
