### PR TITLE
ON HOLD - Post Release: Alpine Bulk Actions (New Functionality)

### PR DESCRIPTION
**Pull request by lrljoe**
Using AlpineJS to setup bulk actions.

New Features:
- Select All On Page

To Do (future improvements)
- Defer/Debounce inputs
- Option for Icon Toggle rather than classic checkbox

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests and did you add any new tests needed for your feature?
2. [x] Did you update all templates (if applicable)?
3. [x] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by lrljoe** [comment]
Check out demo on https://tabledemo.lowerrocklabs.com/tailwind - believe this should be working smoothly now!

**Comment by lrljoe** [comment]
I've moved the x-data for all of the alpine for the wrapper into its own div around the existing div.

Reason being is to allow for users to add their own x-data as an attribute to setComponentWrapperAttributes more easily without interfering.

**Comment by lrljoe** [comment]
I will postpone this until after next release due to quantity already in this next release.

**Comment by lrljoe** [comment]
Needs amends to bring into line with current changes, will refresh and merge into develop by end of week

**Comment by lrljoe** [comment]
Additional amends to allow for the selected items to be deferred to reduce refreshes, estimate is now end of month.

The following items are my focus in this PR:

1) Component does not refresh when adding/removing an item to the Bulk Actions Selected

2) Capability to select current page

3) Capability to select individual items across multiple pages, retain checkbox status and selection.

**Comment by siebsie23** [comment]
Are there any updates on when this PR will be finished?

**Comment by lrljoe** [comment]
Yep, I've got a final round of checks on develop branch for outstanding items

Then this is next on my to-do list for this package.  It is 95% there (in another branch).

**Comment by lrljoe** [comment]
Replaced with #1196

**Pull request closed without merging**
