### PR TITLE
Enhance search filter

### PR DESCRIPTION
**Pull request by lloricode**
Hi @rappasoft 

If this good idea to able to search multiple result in between space

thank you

### CODE REVIEW

**Comment by lloricode** [comment]
if this ok, i will try to fix test

**Comment by rappasoft** [comment]
I think you can already do this using custom search scopes without the need to update the core. Just explode the term by the space and loop it.

**Comment by lloricode** [comment]
> I think you can already do this using custom search scopes without the need to update the core. Just explode the term by the space and loop it.

Thanks for idea, but i have something, can we add configuration in parent class for this? something like separate function so we able to override it in our local base class extending by your?

**Comment by rappasoft** [comment]
The problem is most people just want to search from the string they are entering, whether it be more than one word or not. I think there would be confusion if you're getting multiple search results from one search term because it's like doing `N` different searches.

**Comment by lloricode** [comment]
> The problem is most people just want to search from the string they are entering, whether it be more than one word or not. I think there would be confusion if you're getting multiple search results from one search term because it's like doing `N` different searches.

I see, good point and I understand now, thanks

**Pull request closed without merging**
