### PR TITLE
getSorts() should only return existing and sortable columns

### PR DESCRIPTION
**Pull request by KaulSe**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests and did you add any new tests needed for your feature?
2. [x] Did you update all templates (if applicable)?
3. [x] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. [x] Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

---

The example below should demonstrate the abnormal behavior:
sort-21-07-19-13 07 2023
 

As you can see, the table shows "Applied Filters" even though there are no applied filters... This PR plans only to return "valid" sorts in the `getSorts()` method.

### CODE REVIEW

**Comment by lrljoe** [comment]
I suggest a few adjustments:

1) Create a "getSortableColumns()" in src/Traits/Helpers/ColumnHelpers.php" and add your code to get the Sortable Columns in there instead.
2) Replace your "$this->columns" with the $this->getColumns() method to standardise with the rest of the package.
3) Remove your filter for detecting if a Column is an instance of Column, as this isn't necessary.
4) Use a "reject" approach to clean the collection up, as this is smoother

If you're not comfortable with how to do that, then please let me know, or feel free to jump in the Discord.

Always grateful for contributions!

**Comment by KaulSe** [comment]
@lrljoe Thank you for your review. I don't know about the labels, but the tests are passing so everything seems to be ok?

**Comment by lrljoe** [comment]
Thanks for the amends, @KaulSe - this won't make it into the next release, as there are some additional tests that I do using an enhanced demo environment, but Sorting is top of my list for the release that follows, and I am going to do my best to get the following release out swiftly as a dedicated "Sorting" release!

**Comment by lrljoe** [comment]
So I've made some adjustments to this, and it's in V3, just going through the testing.

Much to @rappasoft 's chagrin, I will probably backport a chunk of fixes/smoothing into v2 from v3, but that's a little while away.

Once v3 is out, I'll add some more detailed comments around my thinking, as I did tweak this a little.

**Comment by lrljoe** [comment]
I've rolled most of this back out of v3, as it caused some issues with label-only columns.

I'm going to revisit it for a v3.x (or possibly a later beta version), as I'm keen to get the actual V3 beta out sooner rather than later.

**Pull request closed without merging**
