### PR TITLE
Optimized imports

### PR DESCRIPTION
**Pull request by edwinvdpol**
Hi there 👋 

This PR includes:
* Use imports where possible (not all)
* Remove unused imports
* Format imports

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by lrljoe** [comment]
Wow, swathe of updates there, but all make sense.

Once the next release is done, then I'll look at merging this into the development branch and releasing, as there's already a lot in the next release

**Comment by lrljoe** [comment]
I've started reviewing this

It's well worth noting, it has no impact on performance if you have imports that aren't used.  Modern PHP "use" isn't the same as old-school "require/include".

It's very likely that I'll butcher this PR somewhat, and add any MISSING namespace imports (e.g. Closure)

**Comment by edwinvdpol** [comment]
Do you use an IDE like PHPStorm, if you don't mind me asking? It shows me ... kinda much stuff on things that could me improved. As I use this package for the company I work for, I would like to optimize the code futher. Like this PR, it can touch a lot of files, but the changes generally don't have significant impact as such.

What exactly do you mean by superfluous code?
What are the absolute minimum / oldest versions for like example PHP / Laravel you want to support?

**Comment by lrljoe** [comment]
So we support Laravel 10 + 11 in v3, with the various iterations of PHP that are supported by those.

I'm keen to merge this in, but in multiple stages, as I run some separate tests to the main tests.

None of the changes should break anything, but sometimes some of the sites using the package have some oddities in their config, so it can be smoother to merge changes of this size in stages.

**Comment by lrljoe** [comment]
I've merged this into development for testing purposes

**Pull request merged**
