### PR TITLE
Fixes Bulk Action Button dropdown for BS5

### PR DESCRIPTION
**Pull request by nessimabadi**
Adds Alpine.js code for functionality of the Bulk Action dropdown button for the Bootstrap 5 theme

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests and did you add any new tests needed for your feature?
2. [x] Did you update all templates (if applicable)?
3. [x] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by nessimabadi** [comment]
Saw that there's an existing pull request (#789 ) with failed tests with the wontfix tag.
This one has working tests and doesn't have formatting changes

**Comment by nessimabadi** [comment]
Saw that there's an existing pull request (#789) with failed tests with the wontfix tag.
This one has working tests and doesn't have formatting changes

**Comment by rappasoft** [comment]
What is this fixiing? The dropdown seems to work fine just with Bootstrap.

**Comment by nessimabadi** [comment]
HI @rappasoft , found my bug why it wasn't working.
I had renamed the data-bs to data-bootstrap, to fix it had to publish the toolbar blade file and edit it.

The implementation I did was to handle the dropdown with AlpineJS.

I'll close the pull request, thanks

**Comment by mithrand0** [comment]
I can confirm, when using Bootstrap 5 with Alpine 3, the bulk actions menu is not showing. No errors in console, it's just not showing the menu when clicking. The other menus, like filters and columns, work fine.

By publishing `toolsbar.blade.php` and implementing the changes from this PR in that file, I can confirm the bulk menu works again.

**Comment by schbudy** [comment]
@mithrand0 Thanks
I already spend hours and still don't know why alpine not working just in the Bulk Actions Dropdown
and now it's working now

**Comment by lrljoe** [comment]
> @mithrand0 Thanks
> I already spend hours and still don't know why alpine not working just in the Bulk Actions Dropdown
> and now it's working now

Is this still actually a bug in v2?  It certainly shouldn't be in v3...

If there's a bug, please raise an issue and it'll get fixed.

**Comment by schbudy** [comment]
I'm still using v2 since updating get me conflict dependencies
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rappasoft/laravel-livewire-tables[v3.0.0-beta.1, ..., v3.4.5] require illuminate/contracts ^10.0|^11.0 -> found illuminate/contracts[v10.0.0, ..., 10.x-dev, v11.0.0, ..., 11.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires rappasoft/laravel-livewire-tables 3.x -> satisfiable by rappasoft/laravel-livewire-tables[v3.0.0-beta.1, ..., v3.4.5].
```
I haven't try v3 so I can't say

**Pull request closed without merging**
