### PR TITLE
Additional AlpineJS Variable for Toolbar Blade - childElementOpen 

### PR DESCRIPTION
**Pull request by lrljoe**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [X] Does your submission pass tests and did you add any new tests needed for your feature?
2. [X] Did you update all templates (if applicable)?
3. [x] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [X] Have you successfully ran tests with your changes locally?

This adds an additional boolean variable to each dropdown in the Toolbar.  As the mouseaway event fires when generated child elements are utilised and clicked on (e.g. Flatpickr, Select2, Dynamic Dropdown), the menu closes, giving a poor user experience.

The variable can be set manually to true (defaults to false), which prevents the menu from closing.

This is only really for developers who are extending the toolbar elements.

No new tests are required, as the default keeps functionality the same as current, and will only be used in additional filters/tools, which should include the relevant tests when utilising the variable.

### CODE REVIEW

**Comment by rappasoft** [comment]
Some docs on how to use this might be good too.

**Comment by lrljoe** [comment]
Yep, I'm planning to add a set of docs on alpine in general, perhaps as a new help section?

Mostly as I've explained a few core concepts like entangling and using the values in columns to people which seem to have been well received and add value.

Just want to avoid cluttering up the core docs which show how straight forward the basics are with complexities that may turn people away.

Happy to take your steer.

**Comment by rappasoft** [comment]
I'm fine with an Alpine help section or maybe an "Extending" section for those custom filter types or whatnot I haven't had the time to look at yet.

**Comment by lrljoe** [comment]
Yeah no worries, I'll make a start on that this eve, as I know at least one other person has produced some custom filters. 

 I was thinking about giving both repos as examples. 

Plus explaining how to go about it yourself

**Pull request merged**
