### PR TITLE
Fix bug #1997 - Found the issue elsewhere also, so I fixed them too.

### PR DESCRIPTION
**Pull request by mrl22**
This pull request is to fix bug #1997 .

I have found this issue in multiple places where there is incorrect brackets in conjunction with coalescing operator (??).

Example:

```PHP
$input1 = false;
$input2 = true;
return ($input1 ?? true || $input2 ?? true); // Will always return value of $input1 unless null
```

Fixed:

```PHP
return (($input1 ?? true) || $input2 ?? true); // Will only return true if either (or both) $input1 or $input2 are null or true.
```

### CODE REVIEW

**Comment by lrljoe** [comment]
Thanks for the contribution, very helpful :)

However -please base your PR on the "development" branch, I've set the tests to run, but please rebase to get this merged in.

**Comment by mrl22** [comment]
Apologies, I am not very familiar with PR’s, I will read up.

**Comment by mrl22** [comment]
Thank you, leave it with me :)

**Comment by lrljoe** [comment]
> Thank you, leave it with me :)

I've replicated your changes I think, please check out this PR to ensure I've mirrored them:
#2016

In your fork, instead of clicking "New Branch", go here:
[https://github.com/mrl22/laravel-livewire-tables/branches](https://github.com/mrl22/laravel-livewire-tables/branches)

Click "New Branch", and then select the "rappasoft/laravel-livewire-tables" repo, then select "development" as the repository.

This will ensure that you are working with the "development" branch, which often has fixes/changes in it that aren't in "master" yet.

**Pull request closed without merging**
