### PR TITLE
Add indeterminate/three state to the selectall checkbox

### PR DESCRIPTION
**Pull request by koohz**
indeterminate

### CODE REVIEW

**Comment by lrljoe** [comment]
I'm actually just finishing off some fixes for the AlpineJS approach to Bulk Actions, once the fixes are all sorted out, then I'll take a quick look at this, and it shouldn't be an issue to get this merged in, thanks for the contribution!

**Comment by koohz** [comment]
> I'm actually just finishing off some fixes for the AlpineJS approach to Bulk Actions, once the fixes are all sorted out, then I'll take a quick look at this, and it shouldn't be an issue to get this merged in, thanks for the contribution!

You are welcome, and great job with this package!

**Comment by lrljoe** [comment]
It's 99% Anthony's work, I'm just lending a hand at the tail end and grabbing some glory haha.

I've pinched a bit of your code, and merged it with the new AlpineJS approach, I just need to do some final tests on it and then it'll get merged into develop, and probably released tomorrow.

**Comment by lrljoe** [comment]
The premise of this is now in develop, please feel free to take a look and let me know what you think.

I had to deviate from your code as the checkbox isn't a wire:model element anymore to help reduce the frequency of DB calls.

Would welcome any feedback you have on the AlpineJS approach in the develop branch, there were a few bugs earlier today, so I recommend that you don't deploy it to your production env immediately.

**Comment by lrljoe** [comment]
So indeterminate checkbox should be present now, I'd welcome some feedback, and if you have any ideas on behaviours/options for behaviours.

At the moment, I'm thinking:
If less than "ALL" is selected
- First click on that top checkbo
    - Selects all on the page (and sets to indeterminate if not already)
- Second Click 
    - Selects all across all pages
- Third click 
    - Deselects all

What are your thoughts to that approach, as you've obviously got an interest.

**Comment by koohz** [comment]
Better than mine

**Comment by lrljoe** [comment]
There's more in the works on this front to allow for customisable behaviour of the bulk actions.

But thank you for the prompt, it's something I genuinely wouldn't have thought of!

I'll close this PR shortly as the functionality is in the core package.  If you spot any other areas that could do with some UX tweaks then feel free to issue another PR!

I am currently working on collapsible columns improvements, which will be in the next release, but otherwise I'd welcome suggestions via a discussion or PR!

**Comment by michaelcerne** [comment]
Unless I'm missing something, this doesn't seem to behave like in the video from @koohz .

Is there a 3rd state implemented now that will show when some (but not all) items are selected? @lrljoe

**Comment by lrljoe** [comment]
There are three states, none, some and all

You can select none, all on page, and all, using the links.

What are you seeing, and what would you like to see ideally, as there may be an existing option, or may be a simple addition to the next release

**Comment by lrljoe** [comment]
> My users are confused by the header checkbox showing as selected when only some rows are selected.
> 
> I'd like to be able to show the header checkbox in an intermediate state, like in the video originally attached to the issue.
> 
> So...
> 
> If no items are selected: Header checkbox unselected
> If some items are selected: Header checkbox in an intermediate state ("/", "-", etc.)
> If all items are selected: Header checkbox in selected state

This is how it works at the moment (has an intermediate state), not sure what the additional ask is here.  
Can you share which version you're using, pagination method, and a screen capture of the behaviour please?

**Comment by lrljoe** [comment]
I'll look at this one hopefully in the next two weeks along with a few other bugfix backports

**Pull request closed without merging**
