### PR TITLE
READY - Filters - Multiple PRs Combined (Fixes & New Functionality)

### PR DESCRIPTION
**Pull request by lrljoe**
This is an alternative PR, as some of the other PRs have conflicts due to overwriting the same files.

- #1080 - Filters - FIX - Restrict AppliedFilters to only return non-empty
- #1108 - Filters - FIX - Using Filter Header/Footer Causes issues with Column Select
-  #1107 - Filters - New Functionality - Set Filter - Custom Filter Pill Blade
- #1110 - Filters - New Functionality - Custom Filter Labels
- #1101 - Filters - New Functionality - SlideDown - Ability to set Start Row and Column Span for filters
- #1087 - Filters - New Functionality - Adding ID to Filter Wrapper in menus to allow for easy targeting

### #1080 - Filters - FIX - Restrict AppliedFilters to only return non-empty
At the moment, a filter will be considered "applied" if it has any value, including the default value. This causes the Pills to appear with a blank value. To avoid this, I've added an additional check for "isEmpty" in the getAppliedFiltersWithValues.

I am somewhat in two minds on this, but figured that using the filter Defaults for anything other than setting up the array keys (i.e. array with keys, but no values) shouldn't really be done, especially as you can apply filter values at component boot with:

---

### #1108 - Filters - FIX - Filter Header/Footer Duplication & Always-Visible Behaviour
When you have the same filter in both header & footer, it will display on screen despite hiding the column, and will shift to another column, and also cause a duplication of that column's filter.

The issue can be seen on the demo instance by

Having two Columns with Secondary Header & Footer Filters (e.g. as in the Name and E-mail Columns)
Add anything into one of the Secondary Header/Footer filters
Hide that Column.
This appears to be occurring due to there being multiple matching wire:key & ID for the same filter, causing the DOM to become... upset?.

This PR introduces new methods:
setFilterPosition(string $position) // Header or Footer
hasCustomPosition(): bool // Does it Have a filter position set?
getCustomPosition(): string // Retrieves the custom position.

There's a new protected string on the Filter.php to hold the position.

The Custom Position is automatically set by the getSecondaryHeaderContents or getFooterContents functions respectively, the Filter Blades then append either header or footer in an appropriate place in the ID & wire:key respectively, blades have been updated for this.

This allows for the same Filter to exist in multiple places in the page.

There may be a better approach, but this is what I came up with!

---

### #1107 - Filters - New Functionality - Set Filter - Custom Pill Blade
The intention is to provide the ability for Custom Pills Blades for Filters, for a couple of reasons:

To allow for customisation of look/feel of Pills on a per-filter basis, without the need to publish the main views, removing some of the issues that crop up due to older published views.
1. To enhance the capability (particularly with Multi-Select or future Filters) to interact with the data more cleanly (removing individual items for example), rather than having to clear a filter completely.

2. To allow for customisation of look/feel of Pills on a per-filter basis, without the need to publish the main views, removing some of the issues that crop up due to older published views.

This adds the following new methods:

#Added to Views\Traits\FilterHelpers
##hasCustomPillBlade
Determines whether the filter has a custom blade for the pills
```php
  /**
   * Determine if filter has a Custom Pill Blade
   *
   * @return bool
   */
  public function hasCustomPillBlade(): bool
  {
      return $this->filterCustomPillBlade != null;
  }
```

##getCustomPillBlade
Retrieves the path for any custom pill blade
```php
/**
 * Get the path to the Custom Pill Blade
 *
 * @return string|null
 */
public function getCustomPillBlade(): ?string
{
    return $this->filterCustomPillBlade ?? null;
}
```

#Added To Views\Traits\FilterConfiguration
```php
/**
 * @param string $blade
 *
 * @return $this
 */
public function setFilterPillBlade(string $blade): self
{
    $this->filterCustomPillBlade = $blade;

    return $this;
}
```

#Added parameter to Views\Filter
```php
    protected ?string $filterCustomPillBlade = null;
```

#filter-pills.blade updated to check (after the checks for applied/null/hidden pills)
```php
@foreach ($component->getAppliedFiltersWithValues() as $filterSelectName => $value)
    @php
        $filter = $component->getFilterByKey($filterSelectName);
    @endphp

    @continue(is_null($filter))
    @continue($filter->isHiddenFromPills())

    @if ($filter->hasCustomPillBlade())
        @include($filter->getCustomPillBlade(), ['filter' => $filter])
    @else
        // Standard Code Here
    @endif
@endforeach
```

---

### #1110 - Filters - New Functionality - Custom filter labels
Removes Filter Labels from the toolbar.blade and moves them into the blade for the filter .
- Adds a new view component for Filter-Label containing the standard filter label code.
- Removes the Filter Label from the toolbar.blade
- Adds the label to the filter blade directly.
- Adds a setCustomFilterLabel() method for Filters (allows you to set a specific blade file for a specific filter instance's label) instead of the default.
This allows for greater customisation of the labels, and easier styling of the labels for those who wish to customise them.
Subsequent versions of this will have setFilterLabelAttributes() - if approved

---

### #1101 - Filters - New Functionality - SlideDown - Ability to set Start Row and Column Span for filters
This brings in a few new methods for styling the filters when filter layout is slide-down.
Namely:

**Traits/Helpers/FilterHelpers.php**
```php
// Determines if any filters have a configuration for SlideDown Row set
->hasFiltersWithSlidedownRows 

// Gets only visible filters, rather than delegating ths to the blade to determine
->getVisibleFilters 

// Gets the filters, in an array, separated by determined row.  If no "row 1" has been set, it will allocate any filters without a defined row, to row 1.
->getFiltersByRow() 
```

**Views/Traits/FilterConfiguration.php**
```php
// Used to Set the Filter Row when SlideDown is used
->setFilterSlidedownRow(Number)  

// Used to Set the Filter Colspan when SlideDown is used
->setFilterSlidedownColspan(Number)  
```

**Views/Helpers/FilterConfiguration.php**
```php
// Determines if the filter has a defined Row
->hasFilterSlidedownRow()

// Finds the Row for the filter
->getFilterSlidedownRow()

// Determines if the filter has a defined Colspan
->hasFilterSlidedownColspan()

// Finds the Colspan for the filter
->getFilterSlidedownColspan()
```

The modifications do take into account the maximum number of columns (depending on Theme and Screen Size), so if you specify beyond the limits, it should break onto the next row gracefully.

E.g.
Two filters with setFilterSlidedownRow(1) and setFilterSlidedownColspan(2) 
**Mobile** the first in the array will win and be listed first, with the second in the array listed beneath it
**Small** listed one under the other
**Medium** listed  one under the other

Two filters with setFilterSlidedownRow(1) and setFilterSlidedownColspan(4) 
**Mobile** the first in the array will win and be listed first, with the second in the array listed beneath it
**Small** listed one under the other
**Medium++** listed one under the other

Note that getFilters is replaced with getVisibleFilters and checks to see if the filter is visible are removed.

---

### #1087 - Filters - New Functionality - Adding ID to Filter Wrapper in menus to allow for easy targeting
To allow for manipulation/targeting of this, either by CSS or JS without impacting on the the wider toolbar elements, only adds an ID to the wrapper for the filter in the toolbar.blade

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests and did you add any new tests needed for your feature?
2. [x] Did you update all templates (if applicable)?
3. [x] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by rappasoft** [comment]
I just want to jump in and acknowledge that I see all of these even if I look like im MIA. I just have a bunch going on. If you can close the ones that are now covered under this so I have a better idea where to start that would be great.

**Comment by lrljoe** [comment]
> 



> I just want to jump in and acknowledge that I see all of these even if I look like im MIA. I just have a bunch going on. If you can close the ones that are now covered under this so I have a better idea where to start that would be great.

Done, and referenced so that you can easily look back over anything in particular.

There's quite a few changes to add new functionality/customisations, and a couple of fixes.

I am in the process of writing some Dusk tests across the whole of Core to make it very straight forward to test all of the core components across various browsers, and TW2/3, BS4/5

**Comment by lrljoe** [comment]
@rappasoft - Just doing some final tests in the demo instance on this one, hang fire on a merge into your develop for an hour :)

**Comment by lrljoe** [comment]
@rappasoft 
So demo of this on [https://filterdemo.lowerrocklabs.com/](https://filterdemo.lowerrocklabs.com/)
E-mail Verified has the following changes
1) Custom Pills Blade
2) Custom Label Blade
3) Custom SlideDown Row
4) Custom SlideDown ColSpan

I'm not sure for custom pills/label whether I should include a stub for publishing perhaps?

**Comment by lrljoe** [comment]
@rappasoft - Note that I've added another minor commit for passing the theme & layout directly to the new Filter Label component, this is just for simplification's sake.

I do have another branch where I've replaced the  "@if ($theme === 'tailwind')" elements with @class instead, just doing some testing across various aspects of it and Laravel versions, but didn't want to add that into this collection.

Any idea on when you'll have a chance to take a peak at this and let me know if anything looks disastrous?  No pressure!

**Comment by lrljoe** [comment]
Sadly too much time is passing between the PR opening, and my automations kicking in to merge various branches in my own fork, so it's causing a lot of pain on my end, appreciate it's my fault for having automations kicking in!

Not too sure what the best option here is!

**Comment by rappasoft** [comment]
@lrljoe i'm going to add you as a collaborator. These PR's are so big I just don't have time to look at them line by line and test locally. If you want you can merge them into develop, and just write me something on how to test them all quick and I'll make the releases.

**Comment by lrljoe** [comment]
> @lrljoe i'm going to add you as a collaborator. These PR's are so big I just don't have time to look at them line by line and test locally. If you want you can merge them into develop, and just write me something on how to test them all quick and I'll make the releases.

That makes perfect sense to me, thanks! I'll merge the relevant pieces from this into develop tomorrow once I unpick what my automation has done to my different commits, and drop you a note on how to test, or if you have a chance to create a branch on the demo repo, then I'll issue a PR onto that with an example of all of the different options.

**Comment by rappasoft** [comment]
I gave you access to that repo too. Just please remember to update the changelog. You can actually make a PR to master when you're ready for a release and just throw testing notes in there. It will require approval to merge anyway.

Thanks again for all your work on this project!

**Comment by lrljoe** [comment]
@rappasoft - due to length of time that the various PRs have been open, my automations have merged various other branches together.

Can you let me know when you think you'll have a chance to look at the various PRs, and I'll make sure that there's a fresh PR for this for then.

> I gave you access to that repo too. Just please remember to update the changelog. You can actually make a PR to master when you're ready for a release and just throw testing notes in there. It will require approval to merge anyway.
> 
> Thanks again for all your work on this project!

No problem,  if you've got a to-do list that you're either working on, or think is high priority and you don't have time for, then drop it somewhere I can see it and I'll see what I can do.  I'm fortunate that I've got a chunk of time where the office isn't being too demanding!

**Comment by rappasoft** [comment]
The changelog has a list of the PR's that are already merged into develop so you can skip those they'll close when master is released.

**Comment by lrljoe** [comment]
Perfect, I'll get myself up to date shortly, ignore any of my unmerged PRs and I'll get them merged appropriately.

Are you happy with moving filter labels into the filter blades by the way?  

It's mostly just to make customising them a touch easier with the customLabelView etc in case anyone wants to add a class to the label (colour etc) and to allow for use of popover Accordion filter display in future.

**Comment by rappasoft** [comment]
I'm good with most things, but i'll review on the master PR. I trust your judgment to keep everything non-breaking, and update the docs too (I'll also obv help when I can)

The one big ticket item I've wanted to tackle is to get all relationship types to work, as well as model attributes, etc.

Let's try to keep the releases as small as possible to keep my review and testing light.

**Comment by lrljoe** [comment]
Definitely agree on small as possible for reviewing.

To kick off, I'll take a look at any outstanding PRs, and merge those into develop where they have tests & docs covering the relevant areas, and where they don't have an adverse impact on the demo environment (which is a fork of your core demo with options for most major features),  and give feedback where they need something else doing.

All types of relationships is definitely a big ticket item, I've tinkered and got a couple of other types working, although not as cleanly as I'd want to issue a PR for just yet.

**Comment by rappasoft** [comment]
Feel free to add more examples to the demo environment as well. That was just a quick example I threw together to help people.

**Comment by lrljoe** [comment]
Yeah will do, I've put together some external toggles for setFilterLayout etc, and added in tailwind 3, so I'll clean it up/document properly then update.

**Pull request closed without merging**
