### PR TITLE
add row number column to tailwind theme

### PR DESCRIPTION
**Pull request by ratiw**
Enable `tailwind` table to show row number by setting 
```php
    $rowNumberEnabled = true;
```

### CODE REVIEW

**Comment by rappasoft** [comment]
What is the use case for this?

**Comment by rappasoft** [comment]
Yes but when you sorted or filtered the row number associated with the rows would change. So you wouldn't be able to say "row with number 5 is the same all the time" so I could see issues. That's why I like having a `sort` column in the demo, its the same number regardless of how its sorted or filtered.

Unless you see some other use I don't see.

**Comment by ratiw** [comment]
Hmm, am I correct that you assumed that the "row number" is the "record ID"? 

If so, that is unintentionally misunderstanding for my implementation. To me, the "row number" is like a line number in the table. It wasn't meant to be locked to any particular record at all. Sorry for the misunderstanding.

**Comment by rappasoft** [comment]
I think it will add a lot of unnecessary code since you need to make it work with the header, secondary header, footer, reordering, etc. Plus you only did the tailwind theme and you would have to do it for bootstrap 4 and 5 as well.

**Pull request closed without merging**
