### PR TITLE
Add linkTo cell setting

### PR DESCRIPTION
**Pull request by fabio-ivona**
Hi @rappasoft 

as usual: you're doing a great work! A lot of livewire datatables packages are showing up, but yours is the one that better balances features and DX!

I'll try to contribute by adding a new `->linkTo(...)` method to a column:

with this PR, during the table columns setup you could do:

```PHP
return [
            //...

            Column::make('Name', 'name')
                ->linkTo(fn($value, $column, $row) => route('pets.edit', $row->id))
                ->searchable(),

            //...
        ];
```

and this will result in the table cell being rendered with this content:

`<a href='http://my.domain/pets/5/edit'>My Pet 5 Name</a>`

So the cell would be clickable and be linked to the url generated by the `->linkTo()` callback:

**Note:** a second parameter for the `->linkTo()` method allows to hint the link target:

```PHP
  Column::make('Name', 'name')
                ->linkTo(fn($value, $column, $row) => route('pets.edit', $row->id), '_blank')
                ->searchable(),
```

What do you think?

### CODE REVIEW

**Comment by rappasoft** [comment]
When would this be more useful than this though? https://rappasoft.github.io/laravel-livewire-tables-docs/rows/Clickable-Rows

**Comment by fabio-ivona** [comment]
This is intended to work on a single cell, a different use case

And, as it would be defined in the Column

**Comment by fabio-ivona** [comment]
This would work on a single cell, so a different use case

**Comment by kevyworks** [comment]
Can we merge this? If the library has like Macro I would go with that approach as well.

**Pull request merged**
