### PR TITLE
fix select rows query

### PR DESCRIPTION
**Pull request by Lupennat**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests and did you add any new tests needed for your feature?
2. [ ] Did you update all templates (if applicable)?
3. [ ] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. [ ] Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

more info on issue https://github.com/rappasoft/laravel-livewire-tables/issues/625

### CODE REVIEW

**Comment by Lupennat** [comment]
@rappasoft any chance to approve this pull request?

**Comment by affektde** [comment]
I think this introduced a bug, when we use columnSearch filter. (https://rappasoft.com/docs/laravel-livewire-tables/v1/columns/column-header-search)

`$this->query()` holds already a search query from a possible columnSearch.

The resulting `wheres` with `and` `or` `and` queries all items with with `title` `%lo%"` in my example.

`selectedRowsQuery` then holds the whole page instead of the one selected item.(id:4046 in my example) 

image

I'll try to find a solution for that, but maybe someone has a quick fix for it.

**Comment by affektde** [comment]
Okay sorry for the noise.

For those who may have the same problem: don't use `orWhere` in your `columnSearch` queries.

image

**Comment by Lupennat** [comment]
Hi @affektde PR, only change behaviour when "select All" Checkbox is enabled. Are you sure the problem is related to the pull request?

**Comment by Lupennat** [comment]
@affektde you can use where with closure like this:

```php
$query->where(function($query) {
    $query->where('title', 'like', '%' . $value . '%')
          ->orWhere('version', 'like', '%' . $value . '%');
});
```

**Pull request merged**
