### PR TITLE
fix results count on tailwind theme

### PR DESCRIPTION
**Pull request by bdelamatre**
Ensures that a results count is displayed even when a) there is less than one page of results and b) pagination is disabled

### CODE REVIEW

**Comment by rappasoft** [comment]
Hmm we should probably do this for all of the themes.

**Comment by bdelamatre** [comment]
A quick smoke test and looked like this was already working somehow for bootstrap and the current pagination views. Not sure why the difference.

**Comment by rappasoft** [comment]
Hmm for me pagination does not show lol. I'll dig into it.

**Comment by rappasoft** [comment]
Bootstrap 4 and 5 show nothing for me if paginationEnabled is false, also just noticed, tailwind pagination has the results and links reversed from that Bootstrap has.

**Comment by molnarjg** [comment]
@rappasoft Is it possible to only show either the pager buttons OR the "Showing .." text with the pagination buttons on the right? Having them all at once with Tailwind is a little bit too much:
image

**Comment by rappasoft** [comment]
It's normally just the right side of your screenshot. I don't know how you got both simple and advanced pagination to show up at once?

**Pull request merged**
